services:
  backend:
    build: 
      context: ./backend
    container_name: leilao_backend
    restart: always
    networks:
      - easypanel

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=${VITE_API_BASE:-http://localhost:3001/api}
    container_name: leilao_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - easypanel

networks:
  easypanel:
    external: true
