services:
  backend:
    build: 
      context: ./backend
    restart: always
    environment:
      - host=${host:-}
      - port=${port:-5432}
      - database=${database:-}
      - user=${user:-}
      - password=${password:-}
      - sslmode=${sslmode:-disable}
      - SERVER_PORT=${SERVER_PORT:-3001}
    networks:
      - easypanel

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=${VITE_API_BASE:-http://localhost:3001/api}
    restart: always
    depends_on:
      - backend
    networks:
      - easypanel

networks:
  easypanel:
    external: true
